Use /usr/local/lib/R as default location for r-home for consistency's sake
svn path=/trunk/rkward/; revision=454

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1070,7 +1070,6 @@ Optional Packages:
   --with-qt-dir=DIR       where the root of Qt is installed
   --with-qt-includes=DIR  where the Qt includes are.
   --with-qt-libraries=DIR where the Qt library is installed.
-  --r-home=DIR            specify location of R_HOME directory
   --without-arts          build without aRts default=yes
 
 Some influential environment variables:
@@ -6715,7 +6714,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6718 "configure"' > conftest.$ac_ext
+  echo '#line 6717 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7356,7 +7355,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:7359:" \
+echo "$as_me:7358:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -8382,11 +8381,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8385: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8384: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8389: \$? = $ac_status" >&5
+   echo "$as_me:8388: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -8615,11 +8614,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8618: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8617: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8622: \$? = $ac_status" >&5
+   echo "$as_me:8621: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -8682,11 +8681,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8685: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8684: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8689: \$? = $ac_status" >&5
+   echo "$as_me:8688: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10785,7 +10784,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10788 "configure"
+#line 10787 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10883,7 +10882,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10886 "configure"
+#line 10885 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13020,11 +13019,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13023: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13022: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13027: \$? = $ac_status" >&5
+   echo "$as_me:13026: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13087,11 +13086,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13090: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13089: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13094: \$? = $ac_status" >&5
+   echo "$as_me:13093: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14416,7 +14415,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14419 "configure"
+#line 14418 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14514,7 +14513,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14517 "configure"
+#line 14516 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15337,11 +15336,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15340: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15339: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15344: \$? = $ac_status" >&5
+   echo "$as_me:15343: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15404,11 +15403,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15407: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15406: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15411: \$? = $ac_status" >&5
+   echo "$as_me:15410: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17360,11 +17359,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17363: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17362: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17367: \$? = $ac_status" >&5
+   echo "$as_me:17366: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -17593,11 +17592,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17596: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17595: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17600: \$? = $ac_status" >&5
+   echo "$as_me:17599: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -17660,11 +17659,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17663: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17662: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17667: \$? = $ac_status" >&5
+   echo "$as_me:17666: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19763,7 +19762,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19766 "configure"
+#line 19765 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19861,7 +19860,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19864 "configure"
+#line 19863 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -27868,7 +27867,7 @@ for i in $jpeg_incdirs;
 do
   for j in jpeglib.h;
   do
-    echo "configure: 27871: $i/$j" >&5
+    echo "configure: 27870: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       jpeg_incdir=$i
@@ -28173,7 +28172,7 @@ for i in $qt_incdirs;
 do
   for j in $kde_qt_header;
   do
-    echo "configure: 28176: $i/$j" >&5
+    echo "configure: 28175: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       qt_incdir=$i
@@ -28910,23 +28909,22 @@ done
 
 
 
-echo "$as_me:$LINENO: checking for R_HOME directory" >&5
-echo $ECHO_N "checking for R_HOME directory... $ECHO_C" >&6
-
-# Check whether --with-r-home or --without-r-home was given.
-if test "${with_r_home+set}" = set; then
-  withval="$with_r_home"
-  use_r_home="$withval"
-else
-  use_r_home="/usr/lib/R"
-
-fi;
+echo "$as_me:$LINENO: checking whether R_HOME directory exists" >&5
+echo $ECHO_N "checking whether R_HOME directory exists... $ECHO_C" >&6
+AC_ARG(r-home,  --r-home=DIR            specify location of R_HOME directory,
+  use_r_home="$withval",
+  use_r_home="/usr/local/lib/R"
+)
 r_home=
 if test -d "$use_r_home"; then
    R_HOMEDIR="$use_r_home"
 else
-   { { echo "$as_me:$LINENO: error: \"$use_r_home does not exist as a directory!\"" >&5
-echo "$as_me: error: \"$use_r_home does not exist as a directory!\"" >&2;}
+   { { echo "$as_me:$LINENO: error:
+   $use_r_home does not exist as a directory!
+   Check your installation of R, and use --with-r-home to specify the correct location." >&5
+echo "$as_me: error:
+   $use_r_home does not exist as a directory!
+   Check your installation of R, and use --with-r-home to specify the correct location." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -28938,11 +28936,17 @@ echo "${ECHO_T}$use_r_home" >&6
 echo "$as_me:$LINENO: checking for libR.so" >&5
 echo $ECHO_N "checking for libR.so... $ECHO_C" >&6
 if test -f "$R_HOMEDIR/lib/libR.so"; then
-   echo "$as_me:$LINENO: result: found" >&5
-echo "${ECHO_T}found" >&6
+   echo "$as_me:$LINENO: result: $R_HOMEDIR/lib/libR.so" >&5
+echo "${ECHO_T}$R_HOMEDIR/lib/libR.so" >&6
 else
-   { { echo "$as_me:$LINENO: error: \"$R_HOMEDIR/lib/libR.so does not exist. Check whether you have compiled R with shared library\"" >&5
-echo "$as_me: error: \"$R_HOMEDIR/lib/libR.so does not exist. Check whether you have compiled R with shared library\"" >&2;}
+   { { echo "$as_me:$LINENO: error:
+   $R_HOMEDIR/lib/libR.so does not exist.
+   Check whether you have compiled R with shared library,
+   and the --with-r-home setting was detected correctly above." >&5
+echo "$as_me: error:
+   $R_HOMEDIR/lib/libR.so does not exist.
+   Check whether you have compiled R with shared library,
+   and the --with-r-home setting was detected correctly above." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -29036,7 +29040,7 @@ for i in $kde_incdirs;
 do
   for j in $kde_check_header;
   do
-    echo "configure: 29039: $i/$j" >&5
+    echo "configure: 29043: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_incdir=$i
@@ -29066,7 +29070,7 @@ for i in $kde_libdirs;
 do
   for j in $kde_check_lib;
   do
-    echo "configure: 29069: $i/$j" >&5
+    echo "configure: 29073: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_libdir=$i
@@ -29084,7 +29088,7 @@ for i in $kde_libdirs;
 do
   for j in "kde3/plugins/designer/kdewidgets.la";
   do
-    echo "configure: 29087: $i/$j" >&5
+    echo "configure: 29091: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_widgetdir=$i
@@ -30474,7 +30478,7 @@ for i in $kde_sharedirs;
 do
   for j in apps/ksgmltools2/customization/kde-chunk.xsl;
   do
-    echo "configure: 30477: $i/$j" >&5
+    echo "configure: 30481: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       KDE_XSL_STYLESHEET=$i
@@ -32240,11 +32244,6 @@ cat >>$CONFIG_STATUS <<\_ACEOF
 
 { (exit 0); exit 0; }
 _ACEOF
-if test "x$with_fast_perl" = "xyes"; then    
-  perl -i.bak $ac_aux_dir/conf.change.pl $CONFIG_STATUS    \
-    || mv $CONFIG_STATUS.bak $CONFIG_STATUS    
-  rm -f $CONFIG_STATUS.bak
-fi    
 chmod +x $CONFIG_STATUS
 ac_clean_files=$ac_clean_files_save
 
